erDiagram
    MUSTERI ||--o{ SIPARIS : verir
    SIPARIS ||--|{ SIPARIS_DETAY : icerir
    URUN ||--o{ SIPARIS_DETAY : listelenir
    SIPARIS ||--|| ODEME : tamamlanir

    MUSTERI {
        string musteriId PK
        string adSoyad
        string eposta
        string telefon
    }

    SIPARIS {
        int siparisNo PK
        string musteriId FK
        datetime siparisTarihi
        float toplamTutar
        string durum
    }

    SIPARIS_DETAY {
        int detayId PK
        int siparisNo FK
        string urunKodu FK
        int adet
        float birimFiyat
    }

    URUN {
        string urunKodu PK
        string urunAdi
        float fiyat
        int stokAdedi
    }

    ODEME {
        string odemeId PK
        int siparisNo FK
        string odemeTuru
        float tutar
        datetime odemeZamani
    }
